const menu = [
  {
    id: 1,
    title: 'Injera Firfir',
    category: 'breakfast',
    price: 80.00,
    img: './images/item-1.jpeg',
    desc: `Injera Firfir is an Ethiopian food typically served for breakfast. It is generally made with shredded flat injera, spiced clarified butter (called niter kibbeh in Amharic), and the hot spice berbere. The injera is torn into small bite size rolls or pieces, marinated in the prepared stew. `,
  },
  {
    id: 2,
    title: 'Kitfo',
    category: 'lunch',
    price: 300,
    img: './images/item-2.jpeg',
    desc: `Kitfo, a dish made from raw minced beef, It’s a food that’s often eaten on special occasions, with good friends or family. You can either order leb leb, which is very slightly cooked, or the normal Kitfo which is completely raw. The minced meat is mixed with mitmita, a blend of spices, and fresh butter, and served with enjera, and kocho.`,
  },
  {
    id: 3,
    title: 'Acacia Dry Red',
    category: 'Wine',
    price: 196,
    img: './images/item-3.jpeg',
    desc: `A deep ruby red color with warm spicy notes. This dry wine is enjoyable with roast beef or Ethiopian Doro wet, or just by itself.`,
  },
  {
    id: 4,
    title: 'CHECHEBSA WITH EGG',
    category: 'breakfast',
    price: 110,
    img: './images/item-4.jpeg',
    desc: `A flaky and oily fried bread shredded into bite size pieces, then fried up with some butter and just a hint of berbere for flavoring. It is served with a side of fresh honey, topped with scrambled egg, and a bowl of plain yogurt. `,
  },
  {
    id: 5,
    title: 'Kikil',
    category: 'lunch',
    price: 260,
    img: './images/item-5.jpeg',
    desc: `Kikil is a mild stew with potatoes, carrot and lamb bones that is slowly cooked to get all the flavors from the bones. It is a great meal to use as a substitute for chicken soup offered to those feeling under the weather.`,
  },
  {
    id: 6,
    title: 'Rift Valley Chardonnay',
    category: 'Wine',
    price: 201,
    img: './images/item-6.jpeg',
    desc: `White wine with a touch of golden color. Flavors of peach and apricot. Crisp and refreshing with dominant aromas of honey. As an aperitif with seafood, cheese and Ethiopian Assa tibs and local fish dishes.`,
  },
  {
    id: 7,
    title: 'Dullet ',
    category: 'breakfast',
    price: 100,
    img: './images/item-7.jpeg',
    desc: `Ground beef, tripe, and liver cooked with mitmita, Ethiopian butter and spices, onions, jalapeños, and served with homemade cheese.`,
  },
  {
    id: 8,
    title: 'Tibis',
    category: 'lunch',
    price: 260,
    img: './images/item-8.jpeg',
    desc: `Cubes of beef sautéed with onions, tomatoes, jalapeños, garlic, and house sauce. * Can be ordered medium (LEGA) or well done (DAREK).`,
  },
  {
    id: 9,
    title: 'Axumite',
    category: 'Wine',
    price: 190,
    img: './images/item-9.jpeg',
    desc: `Axumit wine received its beloved name from an ancient civilization called AXUM. This meticulously made semi-sweet red wine is made with Sangiovese and Grenache noir red grapes variety. The sweet tatse gives the wine lighteness and easy to drink feel.`,
  },
];
export default menu;